version: '3.8'

services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_glowup
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./bd/backup.sql:/docker-entrypoint-initdb.d/backup.sql
    networks:
      - network_gu

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USER: 'root'
      DB_PASSWORD: 'root'
      DB_NAME: db_glowup
      DB_CONNECTION_LIMIT: 20
    depends_on:
      - mariadb
    networks:
      - network_gu

  frontend:
    build: ./
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - network_gu

networks:
  network_gu:
    driver: bridge

volumes:
  mariadb_data:
